/// structmd-codegen — Generate Rust config loaders from structured markdown schemas.
///
/// Reads a .schema.conf.md file and emits a .rs file containing:
/// - Typed structs matching the BNF productions
/// - A parse() function that walks a structmd::parse::Document into those structs

use structmd::schema::{
    H1Schema, NamePattern, Quantity, Schema, SectionSchema, ValueType, load_schema,
};
use std::fmt::Write;
use std::path::Path;

/// Generate Rust source from schema text (for testing).
pub fn generate_from_text(schema_text: &str, name: &str) -> String {
    let schema = load_schema(schema_text, name)
        .unwrap_or_else(|e| panic!("invalid schema: {e}"));
    emit_code(&schema)
}

pub fn generate(schema_path: &str, output_path: &str) {
    let text = std::fs::read_to_string(schema_path)
        .unwrap_or_else(|e| panic!("cannot read schema {schema_path}: {e}"));

    let name = Path::new(schema_path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("config")
        .split('.')
        .next()
        .unwrap_or("config");

    let schema = load_schema(&text, name)
        .unwrap_or_else(|e| panic!("invalid schema {schema_path}: {e}"));

    let code = emit_code(&schema);
    std::fs::write(output_path, code)
        .unwrap_or_else(|e| panic!("cannot write {output_path}: {e}"));
}

/// Generate Rust source code from a parsed schema.
pub fn emit_code(schema: &Schema) -> String {
    let mut out = String::new();

    writeln!(out, "// Generated by structmd-codegen — do not edit").unwrap();
    writeln!(out).unwrap();

    // Collect all struct definitions needed
    let root_name = to_pascal_case(&schema.name) + "Config";

    // If there's only one H1 with no production name, flatten it into the root struct
    let flatten = schema.nodes.len() == 1 && schema.nodes[0].production_name.is_none();

    if flatten {
        let h1 = &schema.nodes[0];
        writeln!(out, "#[derive(Debug, Default)]").unwrap();
        writeln!(out, "pub struct {} {{", root_name).unwrap();
        for sec in &h1.children {
            let field = section_field_name(sec);
            let child_type = section_type_name(sec);
            let rust_type = wrap_quantity(&child_type, sec.quantity);
            writeln!(out, "    pub {}: {},", field, rust_type).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        for sec in &h1.children {
            emit_section_struct(sec, schema, &mut out);
        }
    } else {
        writeln!(out, "#[derive(Debug, Default)]").unwrap();
        writeln!(out, "pub struct {} {{", root_name).unwrap();
        for h1 in &schema.nodes {
            let field = h1_field_name(h1);
            let type_name = h1_type_name(h1);
            let rust_type = wrap_quantity(&type_name, h1.quantity);
            writeln!(out, "    pub {}: {},", field, rust_type).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        for h1 in &schema.nodes {
            emit_h1_structs(h1, schema, &mut out);
        }
    }

    // Emit the parse function
    emit_parse_fn(schema, &root_name, &mut out);

    out
}

fn emit_h1_structs(h1: &H1Schema, schema: &Schema, out: &mut String) {
    let type_name = h1_type_name(h1);
    let has_props = h1.expects_properties;
    let has_children = !h1.children.is_empty();

    if has_props || has_children {
        writeln!(out, "#[derive(Debug, Default)]").unwrap();
        writeln!(out, "pub struct {} {{", type_name).unwrap();

        // H1-level property fields
        if has_props {
            let props = h1
                .properties
                .as_ref()
                .unwrap_or(&schema.global_properties);
            for (key, prop) in props {
                let rust_type = value_type_to_rust(&prop.value_type);
                let is_list = matches!(prop.value_type, ValueType::List(_));
                let rust_type = if is_list {
                    rust_type
                } else if prop.default.is_some() && !prop.required {
                    rust_type
                } else if !prop.required {
                    format!("Option<{}>", rust_type)
                } else {
                    rust_type
                };
                writeln!(out, "    pub {}: {},", key, rust_type).unwrap();
            }
        }

        // Child section fields
        for sec in &h1.children {
            let field = section_field_name(sec);
            let child_type = section_type_name(sec);
            let rust_type = wrap_quantity(&child_type, sec.quantity);
            writeln!(out, "    pub {}: {},", field, rust_type).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        for sec in &h1.children {
            emit_section_struct(sec, schema, out);
        }
    }
}

fn emit_section_struct(sec: &SectionSchema, schema: &Schema, out: &mut String) {
    let type_name = section_type_name(sec);

    writeln!(out, "#[derive(Debug, Default)]").unwrap();
    writeln!(out, "pub struct {} {{", type_name).unwrap();

    // Name field for dynamic sections
    if sec.name_pattern.is_dynamic() {
        writeln!(out, "    pub name: String,").unwrap();
    }

    // Prose field if expected
    if sec.expects_prose {
        writeln!(out, "    pub prose: Option<String>,").unwrap();
    }

    // Property fields
    let props = sec
        .properties
        .as_ref()
        .unwrap_or(&schema.global_properties);
    for (key, prop) in props {
        let rust_type = value_type_to_rust(&prop.value_type);
        let is_list = matches!(prop.value_type, ValueType::List(_));
        let rust_type = if is_list {
            rust_type // lists default to empty vec, never Option
        } else if prop.default.is_some() && !prop.required {
            rust_type // has default, always populated
        } else if !prop.required {
            format!("Option<{}>", rust_type)
        } else {
            rust_type
        };
        writeln!(out, "    pub {}: {},", key, rust_type).unwrap();
    }

    // Child section fields
    for child in &sec.children {
        let field = section_field_name(child);
        let child_type = section_type_name(child);
        let rust_type = wrap_quantity(&child_type, child.quantity);
        writeln!(out, "    pub {}: {},", field, rust_type).unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Recurse for child structs
    for child in &sec.children {
        emit_section_struct(child, schema, out);
    }
}

// ── Parse function generation ──

fn emit_parse_fn(schema: &Schema, root_name: &str, out: &mut String) {
    let flatten = schema.nodes.len() == 1 && schema.nodes[0].production_name.is_none();

    // Inner function that takes errors by ref
    let inner_fn = format!("parse_{}_inner", to_snake_case(root_name));
    writeln!(out, "pub fn parse(text: &str) -> Result<{}, Vec<String>> {{", root_name).unwrap();
    writeln!(out, "    let doc = structmd::parse::parse(text);").unwrap();
    writeln!(out, "    let mut errors = Vec::new();").unwrap();
    writeln!(out, "    let result = {inner_fn}(&doc, &mut errors);").unwrap();
    writeln!(out, "    if errors.is_empty() {{ Ok(result) }} else {{ Err(errors) }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {inner_fn}(doc: &structmd::parse::Document, errors: &mut Vec<String>) -> {} {{", root_name).unwrap();
    writeln!(out).unwrap();

    if flatten {
        let h1 = &schema.nodes[0];
        // Get sections from the first (only) H1
        if let Some(ref text) = h1.text {
            writeln!(out, "    let sections = doc.nodes.iter()").unwrap();
            writeln!(out, "        .find(|n| n.heading.as_ref().map_or(false, |h| h.text == \"{text}\"))").unwrap();
            writeln!(out, "        .map(|n| n.sections.as_slice())").unwrap();
            writeln!(out, "        .unwrap_or(&[]);").unwrap();
        } else {
            writeln!(out, "    let sections = doc.nodes.first().map(|n| n.sections.as_slice()).unwrap_or(&[]);").unwrap();
        }
        writeln!(out).unwrap();

        // Extract child sections directly
        for sec in &h1.children {
            emit_section_extraction(sec, schema, out);
        }

        writeln!(out, "    {} {{", root_name).unwrap();
        for sec in &h1.children {
            let field = section_field_name(sec);
            writeln!(out, "        {},", field).unwrap();
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Emit parse functions for children
        for sec in &h1.children {
            emit_section_parse_fn(sec, schema, out);
        }
    } else {
        // Multi-H1: parse each H1 node
        for (i, h1) in schema.nodes.iter().enumerate() {
            let field = h1_field_name(h1);
            let type_name = h1_type_name(h1);
            let fn_name = to_snake_case(&type_name);

            if let Some(ref text) = h1.text {
                writeln!(out, "    let h1_{i} = doc.nodes.iter().find(|n| n.heading.as_ref().map_or(false, |h| h.text == \"{text}\"));").unwrap();
            } else {
                writeln!(out, "    let h1_{i} = doc.nodes.get({i});").unwrap();
            }

            match h1.quantity {
                Quantity::Optional | Quantity::ZeroOrMore => {
                    writeln!(out, "    let {field} = if let Some(node) = h1_{i} {{").unwrap();
                    writeln!(out, "        Some(parse_{fn_name}(node, errors))").unwrap();
                    writeln!(out, "    }} else {{").unwrap();
                    writeln!(out, "        None").unwrap();
                    writeln!(out, "    }};").unwrap();
                }
                _ => {
                    let h1_text = h1.text.as_deref().unwrap_or("(untitled)");
                    writeln!(out, "    let {field} = if let Some(node) = h1_{i} {{").unwrap();
                    writeln!(out, "        parse_{fn_name}(node, errors)").unwrap();
                    writeln!(out, "    }} else {{").unwrap();
                    writeln!(out, "        errors.push(\"missing required section: # {h1_text}\".into());").unwrap();
                    writeln!(out, "        Default::default()").unwrap();
                    writeln!(out, "    }};").unwrap();
                }
            }
            writeln!(out).unwrap();
        }

        writeln!(out, "    {} {{", root_name).unwrap();
        for h1 in &schema.nodes {
            let field = h1_field_name(h1);
            writeln!(out, "        {},", field).unwrap();
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        for h1 in &schema.nodes {
            emit_h1_parse_fn(h1, schema, out);
        }
    }
}

fn emit_h1_parse_fn(h1: &H1Schema, schema: &Schema, out: &mut String) {
    let type_name = h1_type_name(h1);
    let fn_name = to_snake_case(&type_name);

    writeln!(out, "fn parse_{fn_name}(node: &structmd::parse::H1Node, errors: &mut Vec<String>) -> {type_name} {{").unwrap();
    writeln!(out, "    let sections = &node.sections;").unwrap();

    // Extract H1-level properties
    if h1.expects_properties {
        let props = h1.properties.as_ref().unwrap_or(&schema.global_properties);
        for (key, prop) in props {
            let find = format!("node.properties.iter().find(|p| p.key == \"{key}\").map(|p| p.value.clone())");
            emit_property_extraction(key, prop, &find, out);
        }
    }

    for sec in &h1.children {
        emit_section_extraction(sec, schema, out);
    }

    writeln!(out, "    {} {{", type_name).unwrap();
    if h1.expects_properties {
        let props = h1.properties.as_ref().unwrap_or(&schema.global_properties);
        for (key, _) in props {
            writeln!(out, "        {},", key).unwrap();
        }
    }
    for sec in &h1.children {
        let field = section_field_name(sec);
        writeln!(out, "        {},", field).unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Emit parse functions for child sections
    for sec in &h1.children {
        emit_section_parse_fn(sec, schema, out);
    }
}

fn emit_section_extraction(sec: &SectionSchema, _schema: &Schema, out: &mut String) {
    let field = section_field_name(sec);
    let type_name = section_type_name(sec);
    let fn_name = to_snake_case(&type_name);

    match &sec.name_pattern {
        NamePattern::Exact(name) => {
            // Find by exact heading match
            writeln!(out, "    let {field} = sections.iter()").unwrap();
            writeln!(out, "        .find(|s| s.heading.text == \"{name}\")").unwrap();
            writeln!(out, "        .map(|s| parse_{fn_name}(s, errors));").unwrap();
            match sec.quantity {
                Quantity::Optional | Quantity::ZeroOrMore => {}
                _ => {
                    writeln!(out, "    let {field} = match {field} {{").unwrap();
                    writeln!(out, "        Some(v) => v,").unwrap();
                    writeln!(out, "        None => {{").unwrap();
                    writeln!(out, "            errors.push(\"missing required section: ## {name}\".into());").unwrap();
                    writeln!(out, "            return Default::default();").unwrap();
                    writeln!(out, "        }}").unwrap();
                    writeln!(out, "    }};").unwrap();
                }
            }
        }
        _ => {
            // Collect all matching sections
            writeln!(out, "    let {field}: Vec<{type_name}> = sections.iter()").unwrap();
            writeln!(out, "        .filter(|s| s.heading.level == {})  ", sec.level).unwrap();
            writeln!(out, "        .map(|s| parse_{fn_name}(s, errors))").unwrap();
            writeln!(out, "        .collect();").unwrap();
            if matches!(sec.quantity, Quantity::OneOrMore) {
                writeln!(out, "    if {field}.is_empty() {{").unwrap();
                writeln!(out, "        errors.push(\"expected at least one {} section\".into());", field).unwrap();
                writeln!(out, "    }}").unwrap();
            }
        }
    }
}

fn emit_section_parse_fn(sec: &SectionSchema, schema: &Schema, out: &mut String) {
    let type_name = section_type_name(sec);
    let fn_name = to_snake_case(&type_name);

    writeln!(out, "fn parse_{fn_name}(sec: &structmd::parse::Section, errors: &mut Vec<String>) -> {type_name} {{").unwrap();

    // Extract name for dynamic sections
    if sec.name_pattern.is_dynamic() {
        writeln!(out, "    let name = sec.heading.text.clone();").unwrap();
    }

    // Extract prose
    if sec.expects_prose {
        writeln!(out, "    let prose = sec.prose.clone();").unwrap();
    }

    // Extract properties
    let props = sec
        .properties
        .as_ref()
        .unwrap_or(&schema.global_properties);
    for (key, prop) in props {
        let find = format!("sec.properties.iter().find(|p| p.key == \"{key}\").map(|p| p.value.clone())");
        emit_property_extraction(key, prop, &find, out);
    }

    // Extract child sections
    for child in &sec.children {
        emit_child_extraction(child, schema, out);
    }

    // Build struct
    writeln!(out, "    {} {{", type_name).unwrap();
    if sec.name_pattern.is_dynamic() {
        writeln!(out, "        name,").unwrap();
    }
    if sec.expects_prose {
        writeln!(out, "        prose,").unwrap();
    }
    for (key, _) in props {
        writeln!(out, "        {},", key).unwrap();
    }
    for child in &sec.children {
        let field = section_field_name(child);
        writeln!(out, "        {},", field).unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Recurse for child sections
    for child in &sec.children {
        emit_section_parse_fn(child, schema, out);
    }
}

fn emit_property_extraction(key: &str, prop: &structmd::schema::PropertySchema, find: &str, out: &mut String) {
    use structmd::schema::ValueType;
    match &prop.value_type {
        ValueType::Bool => {
            if let Some(ref default) = prop.default {
                writeln!(out, "    let {key} = {find}.map(|v| v == \"true\").unwrap_or({default});").unwrap();
            } else if prop.required {
                writeln!(out, "    let {key} = match {find} {{").unwrap();
                writeln!(out, "        Some(v) => v == \"true\",").unwrap();
                writeln!(out, "        None => {{ errors.push(\"missing required property '{key}'\".into()); false }}").unwrap();
                writeln!(out, "    }};").unwrap();
            } else {
                writeln!(out, "    let {key} = {find}.map(|v| v == \"true\");").unwrap();
            }
        }
        ValueType::Integer => {
            if prop.required {
                writeln!(out, "    let {key} = match {find} {{").unwrap();
                writeln!(out, "        Some(v) => v.parse::<i64>().unwrap_or_else(|_| {{ errors.push(\"'{key}' must be an integer\".into()); 0 }}),").unwrap();
                writeln!(out, "        None => {{ errors.push(\"missing required property '{key}'\".into()); 0 }}").unwrap();
                writeln!(out, "    }};").unwrap();
            } else {
                writeln!(out, "    let {key} = {find}.and_then(|v| v.parse::<i64>().ok());").unwrap();
            }
        }
        ValueType::List(_) => {
            writeln!(out, "    let {key}: Vec<String> = {find}").unwrap();
            writeln!(out, "        .map(|v| v.split(',').map(|s| s.trim().to_string()).filter(|s| !s.is_empty()).collect())").unwrap();
            writeln!(out, "        .unwrap_or_default();").unwrap();
        }
        _ => {
            if let Some(ref default) = prop.default {
                writeln!(out, "    let {key} = {find}.unwrap_or_else(|| \"{default}\".into());").unwrap();
            } else if prop.required {
                writeln!(out, "    let {key} = match {find} {{").unwrap();
                writeln!(out, "        Some(v) => v,").unwrap();
                writeln!(out, "        None => {{ errors.push(\"missing required property '{key}'\".into()); String::new() }}").unwrap();
                writeln!(out, "    }};").unwrap();
            } else {
                writeln!(out, "    let {key} = {find};").unwrap();
            }
        }
    }
}

fn emit_child_extraction(sec: &SectionSchema, _schema: &Schema, out: &mut String) {
    let field = section_field_name(sec);
    let type_name = section_type_name(sec);
    let fn_name = to_snake_case(&type_name);

    // Children are always collected from sec.children
    writeln!(out, "    let {field}: Vec<{type_name}> = sec.children.iter()").unwrap();
    writeln!(out, "        .filter(|s| s.heading.level == {})", sec.level).unwrap();
    writeln!(out, "        .map(|s| parse_{fn_name}(s, errors))").unwrap();
    writeln!(out, "        .collect();").unwrap();
}

// ── Naming helpers ──

fn h1_field_name(h1: &H1Schema) -> String {
    h1.production_name
        .as_ref()
        .map(|s| s.clone())
        .or_else(|| h1.text.as_ref().map(|t| to_snake_case(t)))
        .unwrap_or_else(|| "root".to_string())
}

fn h1_type_name(h1: &H1Schema) -> String {
    let base = h1
        .production_name
        .as_ref()
        .map(|s| s.clone())
        .or_else(|| h1.text.as_ref().map(|t| to_snake_case(t)))
        .unwrap_or_else(|| "root".to_string());
    to_pascal_case(&base) + "Config"
}

fn section_field_name(sec: &SectionSchema) -> String {
    sec.production_name
        .as_ref()
        .map(|s| s.clone())
        .or_else(|| match &sec.name_pattern {
            NamePattern::Exact(name) => Some(to_snake_case(name)),
            _ => None,
        })
        .unwrap_or_else(|| format!("section_h{}", sec.level))
}

fn section_type_name(sec: &SectionSchema) -> String {
    let base = sec
        .production_name
        .as_ref()
        .map(|s| s.clone())
        .or_else(|| match &sec.name_pattern {
            NamePattern::Exact(name) => Some(to_snake_case(name)),
            _ => None,
        })
        .unwrap_or_else(|| format!("section_h{}", sec.level));
    to_pascal_case(&base) + "Config"
}

fn wrap_quantity(type_name: &str, qty: Quantity) -> String {
    match qty {
        Quantity::One => type_name.to_string(),
        Quantity::Optional => format!("Option<{}>", type_name),
        Quantity::OneOrMore | Quantity::ZeroOrMore => format!("Vec<{}>", type_name),
    }
}

fn value_type_to_rust(vt: &ValueType) -> String {
    match vt {
        ValueType::String | ValueType::Path | ValueType::Cron | ValueType::Text => {
            "String".to_string()
        }
        ValueType::Enum(_) => "String".to_string(),
        ValueType::Bool => "bool".to_string(),
        ValueType::Integer => "i64".to_string(),
        ValueType::Number => "f64".to_string(),
        ValueType::Label => "String".to_string(),
        ValueType::List(inner) => format!("Vec<{}>", value_type_to_rust(inner)),
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == ' ')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c == '-' || c == ' ' {
            result.push('_');
        } else if c.is_uppercase() && i > 0 {
            result.push('_');
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c.to_lowercase().next().unwrap());
        }
    }
    result
}
